#!/bin/bash

echo "Do you want to skip running tests on modified packages [y/N]: "
read should_skip < /dev/tty

if [ "$should_skip" == "N" ];
then

  echo "Running tests..."

  STAGED=`git diff --name-only --cached`
  package="/package.json"
  git="/.git"
  find_package() {
      parentDirectory=$(dirname $1)
      if [ -f $parentDirectory$package ]; then
          RESULT=$parentDirectory$package
      elif [ -d $parentDirectory$git ]; then
          RESULT=''
      else
          RESULT=$(find_package $parentDirectory)
      fi
      echo $RESULT
  }
  list=()
  set -f; IFS=$'\n'
  for staged in $STAGED; do
      item=$(find_package $staged)
      if [[ -z "$item" ]]; then
          echo skipped $staged
      elif grep -q precommit "$item"; then
          list+=($item)
      fi
  done
  files=$(echo "${list[*]}" | sort -u)
  set +f

  exitCode=0
  for file in $files; do
      fileDirectory=$(dirname $file)
      echo
      echo "[$fileDirectory] > pnpm run -s precommit"
      cd $fileDirectory

      pnpm run -s precommit || {
          echo
          echo "[$fileDirectory] > pre-commit hook failed (add --no-verify to bypass)"
          exitCode=1
      }
      cd -
  done
  if [ $exitCode == 1 ]
  then
    exit 1
  fi

fi